//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcMobileStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        public DonHang()
        {
            this.CT_DonHang = new HashSet<CT_DonHang>();
        }
    
        public int MaDH { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<System.DateTime> NgayMua { get; set; }
        public Nullable<System.DateTime> NgayGiao { get; set; }
        public string TenNguoiNhan { get; set; }
        public string DiaChiNhan { get; set; }
        public string DienThoaiNhan { get; set; }
        public Nullable<bool> HTThanhToan { get; set; }
        public Nullable<decimal> Trigia { get; set; }
        public Nullable<bool> Dagiao { get; set; }
    
        public virtual ICollection<CT_DonHang> CT_DonHang { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
