//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcMobileStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioHang
    {
        public int Id { get; set; }
        public string MaGH { get; set; }
        public int MaSP { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> Thanhtien { get; set; }
        public Nullable<System.DateTime> NgayMua { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
