//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcMobileStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public KhachHang()
        {
            this.BinhLuan = new HashSet<BinhLuan>();
            this.DonHang = new HashSet<DonHang>();
            this.LienHe = new HashSet<LienHe>();
        }
    
        public int MaKH { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string HoTen { get; set; }
        public string DiaChi { get; set; }
        public string DienThoai { get; set; }
        public string CMND { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public Nullable<System.DateTime> NgayDangKy { get; set; }
        public string Avatar { get; set; }
        public bool AnHien { get; set; }
    
        public virtual ICollection<BinhLuan> BinhLuan { get; set; }
        public virtual ICollection<DonHang> DonHang { get; set; }
        public virtual ICollection<LienHe> LienHe { get; set; }
    }
}
