//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcMobileStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LienHe
    {
        public int MaLH { get; set; }
        public Nullable<int> MaKH { get; set; }
        public string Avatar { get; set; }
        public string TenNguoiGui { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayGui { get; set; }
        public Nullable<bool> LuotGui { get; set; }
        public Nullable<bool> DaDocKH { get; set; }
        public Nullable<bool> DaDocAD { get; set; }
        public Nullable<bool> Anhien { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
    }
}
