//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcMobileStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int MaMenu { get; set; }
        public string TenMenu { get; set; }
        public string url { get; set; }
        public Nullable<int> Thutu { get; set; }
    }
}
