//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcMobileStore.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MobileStoreEntities : DbContext
    {
        public MobileStoreEntities()
            : base("name=MobileStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin> Admin { get; set; }
        public DbSet<BinhLuan> BinhLuan { get; set; }
        public DbSet<CT_DonHang> CT_DonHang { get; set; }
        public DbSet<DonHang> DonHang { get; set; }
        public DbSet<GioHang> GioHang { get; set; }
        public DbSet<KhachHang> KhachHang { get; set; }
        public DbSet<LienHe> LienHe { get; set; }
        public DbSet<Menu> Menu { get; set; }
        public DbSet<NhaSanXuat> NhaSanXuat { get; set; }
        public DbSet<PhanQuyen_Admin> PhanQuyen_Admin { get; set; }
        public DbSet<QuangCao> QuangCao { get; set; }
        public DbSet<SanPham> SanPham { get; set; }
        public DbSet<Slider> Slider { get; set; }
        public DbSet<TinTuc> TinTuc { get; set; }
        public DbSet<ThongTin> ThongTin { get; set; }
    }
}
