//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcMobileStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanQuyen_Admin
    {
        public int MaPQ { get; set; }
        public Nullable<int> MaAdmin { get; set; }
        public Nullable<bool> PQ_Menu { get; set; }
        public Nullable<bool> PQ_Slider { get; set; }
        public Nullable<bool> PQ_NhaSanXuat { get; set; }
        public Nullable<bool> PQ_SanPham { get; set; }
        public Nullable<bool> PQ_KhachHang { get; set; }
        public Nullable<bool> PQ_DonHang { get; set; }
        public Nullable<bool> PQ_TinTuc { get; set; }
        public Nullable<bool> PQ_QuangCao { get; set; }
        public Nullable<bool> PQ_LienHe { get; set; }
        public Nullable<bool> PQ_GioiThieu { get; set; }
        public Nullable<bool> PQ_QuanTriAdmin { get; set; }
        public Nullable<bool> PQ_SiteMap { get; set; }
    
        public virtual Admin Admin { get; set; }
    }
}
