//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcMobileStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public SanPham()
        {
            this.BinhLuan = new HashSet<BinhLuan>();
            this.CT_DonHang = new HashSet<CT_DonHang>();
            this.GioHang = new HashSet<GioHang>();
        }
    
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public string UrlHinh { get; set; }
        public string Code1 { get; set; }
        public string UrlHinh360 { get; set; }
        public string Code2 { get; set; }
        public decimal GiaHienTai { get; set; }
        public decimal GiaCu { get; set; }
        public string MoTa { get; set; }
        public string MoTaCT { get; set; }
        public string DanhGiaCT { get; set; }
        public int MaNSX { get; set; }
        public int SoLuongTon { get; set; }
        public int SLDaBan { get; set; }
        public double KhuyenMai { get; set; }
        public Nullable<int> LuotXem { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public bool AnHien { get; set; }
    
        public virtual ICollection<BinhLuan> BinhLuan { get; set; }
        public virtual ICollection<CT_DonHang> CT_DonHang { get; set; }
        public virtual ICollection<GioHang> GioHang { get; set; }
        public virtual NhaSanXuat NhaSanXuat { get; set; }
    }
}
