//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcMobileStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTin
    {
        public int MaTT { get; set; }
        public string code1 { get; set; }
        public string GioiThieu { get; set; }
        public string code2 { get; set; }
        public string sitemap { get; set; }
    }
}
